### ISSUE TITLE
Still getting linting errors when importing with `.ts` extension.

### ISSUE THREAD

**Issue by cjnucette** [fannheyward/coc-deno#7]
I'm still getting error from tsserver when importing `.ts` files, and top level `await`. Is there an option I should set or something?

**Comment by fannheyward** [comment]
Please give a test code that can reproduce this issue.

**Comment by cjnucette** [comment]
I was doing some testing with this:

```javascript
import { serve } from 'https://deno.land/std/http/server.ts';
const s = serve({ port: 8000 });
console.log('http://localhost:8000/');

for await (const req of s) {
  console.log(req.url);
  req.respond({ body: `Hello World\n${req.url}` });
}
```
I get the following errors:
`index.ts|1 col 23 error| [tsserver 2691] An import path cannot end with a '.ts' extension. Consider importing 'https://deno.land/std/http/server' instead. [E]`
and 
`index.ts|5 col 5 error| [tsserver 1103] A 'for-await-of' statement is only allowed within an async function or async generator. [E]`

Thanks.

**Comment by fannheyward** [comment]
1. How do you install `coc-deno`? By `:CocInstall coc-deno`?
2. Tested with your code and there is no first error. Only `for-await-of` error shows.
3. Tested with VSCode+ [Deno](https://marketplace.visualstudio.com/items?itemName=justjavac.vscode-deno) extension, also shows the second error. coc-deno uses the same [typescript-deno-plugin](https://github.com/justjavac/typescript-deno-plugin), so it's not coc-deno error.

**Comment by cdimitroulas** [comment]
I am also getting errors for `.ts` extensions after installing this extension. Not sure if it's other configuration in coc which is causing the issue.

**Comment by cjnucette** [comment]
Ok, let me check, because vscode does the exact same thing. This is weird, but most likely something on my end. Thanks anyways.

**Comment by Seanmclem** [comment]
@cjnucette Still getting all these errors

**Comment by cjnucette** [comment]
@Seanmclem I have to uninstall it, because it breaks coc-tsserve completions for me.

**Comment by Seanmclem** [comment]
> @Seanmclem I have to uninstall it, because it breaks coc-tsserve completions for me. 

What's that? Either way, anyone using deno in vscode is immediately going to have this problem. I hope @fannheyward or anyone can fix it. Probably the folks at vscode

**Comment by fannheyward** [comment]
https://github.com/denoland/deno/issues/4752

**Comment by fannheyward** [comment]
<img width="792" alt="截屏2020-05-07 13 39 20" src="https://user-images.githubusercontent.com/345274/81258401-29c50e00-9068-11ea-81d6-871b20c1a8c5.png">

Fixed in v0.5.0. And add a code action to fix importing error.

**Comment by foisonocean** [comment]
@fannheyward 
Still getting errors after applying the coc action "Convert named imports to namespace import":

![image](https://user-images.githubusercontent.com/15059605/81495172-e1fceb80-92e0-11ea-864d-231af5560e7e.png)

**Comment by cjnucette** [comment]
I can't disable the extension in non-deno typescript files so I'm getting error on regular `imports` like in `import { something} from 'components/something';`. I tried disabling `deno.enable: false` in `CocLocalConfig` with no luck.

**Comment by fannheyward** [comment]
@cjnucette yes, there are errors on non-deno files, but it's not coc-deno's issue, but typescript-deno-plugin, vscode-deno also has this error: https://github.com/justjavac/vscode-deno/issues/70

`:CocList extensions` to list all extensions you have installed, filter `coc-deno`, tab to select `disable` action.

**Comment by foisonocean** [comment]
@fannheyward any suggestions for my previous comment? I'm still getting errors.

**Comment by fannheyward** [comment]
<img width="540" alt="2020-05-12 18 39 22" src="https://user-images.githubusercontent.com/345274/81674509-e7446c80-947f-11ea-8adb-6c6ca0bc95b1.png">

@foisonocean Same error on VSCode + vscode-deno.

**Comment by foisonocean** [comment]
Got it. I suggest keep this issue open until upstream fixed.

**Comment by Seanmclem** [comment]
I had to create a .vscode folder with a settings json in it and enable deno there. is that in the readme?

**Comment by pradyungn** [comment]
Hey, I'm getting this error even after disabling the coc-deno extension from the extensions list
![2020-05-28_16-14](https://user-images.githubusercontent.com/19643050/83203496-68496800-a0fe-11ea-81cc-2a1fd14f38f4.png)
. I'm not sure if this is for the same reason as everyone else, but I think it correlates with this?

**Comment by alextes** [comment]
@pradyungn try uninstalling.

**Comment by alextes** [comment]
@fannheyward can you clarify what you meant by "disable the extension" in #25 . I tried disabling the extension from the coc extensions list but that did nothing. Even after reloading tsserver and the buffer.

**Comment by fannheyward** [comment]
@alextes yes, disable doesn't work. I'll look into this.

**Comment by alextes** [comment]
I'm guessing this boils down to coc-deno manipulating a tsserver config that is global somehow, and leaks to other running neovim instances that are also using tsserver. Perhaps coc is even designed to be using one language server per language which would be problematic here.

@fannheyward any idea where I could start looking to fix this?

**Comment by ZE0TRON** [comment]
For those who get a linting error after enabling coc-deno probably you have another linter that creates that errors It was ALE plugin in my case. Hope this helps.

**Comment by cjnucette** [comment]
Is this extension still based on https://github.com/justjavac/vscode-deno ? Because there is an official one out there https://github.com/denoland/vscode_deno, which seems to integrate previous extensions.

**Comment by fannheyward** [comment]
try v3.0.0, use `deno lsp`.

**Comment by hemedani** [comment]
the error still accurate.

**Comment by hemedani** [comment]
look at version 3.0.1 on [VSCode_deno](https://github.com/denoland/vscode_deno/releases/tag/3.0.1)

**Comment by cjnucette** [comment]
@hemedani You need to either `deno.initializeWorkspace` (which I'm not able to find in my case) or you can create a local `.vim/coc-settings.json` where you must enable deno.

**Comment by hemedani** [comment]
@cjnucette `deno.initializeWorkspace` works with :CocCommand deno.initializeWorkspace` but how can i disable `deno.initializeWorkspace` ?

I'm on the monorepo with react and other typescript code so I want's to enable and disable Deno lsp on some files

**Comment by hemedani** [comment]
it's create `.vim/coc-settings.json` file on the root directory so I should be delete this or move file to Deno project directory !
tanx

**Comment by cjnucette** [comment]
I don't think you can enable/disable deno by file, but by directory. So you should create this file in the directory where your deno project is located.

**Comment by mrxiaozhuox** [comment]
I have the same problem, but it will not happen in VS Code.

**Comment by fannheyward** [comment]
@mrxiaozhuox what's your coc-deno version?

**Comment by mrxiaozhuox** [comment]
@fannheyward The latest version.

**Comment by mrxiaozhuox** [comment]
@fannheyward  coc-deno: 3.4.0 coc-tsserver: 1.7.0 deno: 1.10.1

**Comment by fannheyward** [comment]
@mrxiaozhuox can't reproduce. What's the content of `.vim/coc-settings.json` in your project?
